from test import *


if "__main__":
    # test_short_rainbow()
    # test_long_rainbow()
    # test_short_log()
    # test_red_log()
    # test_gray_scale_log()
    # test_cadre()
    # test_cadre_vert()
    # test_section_jaune()
    # test_section_violet()
    # test_log()
    # test_warn()
    # test_error()
    # test_debug()
    # test_save()
    # test_save_fail()
    # test_chrono()
    # test_date()
    # test_time()
    # simulation_utilisation()
    # test_waiting_animation()
    # test_waiting_time()
    # test_progress_bar()
    demonstration()